### ISSUE TITLE
Uncaught TypeError: Cannot set properties of undefined (setting 'directiveAttributes') 

### ISSUE THREAD

**Issue by mbret** [remarkjs/remark-directive#13] opened 2023-09-25 12:33 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

3.0.0

### Steps to reproduce

Need:
- react project
- react markdown library

write something like `::body2[content]{center}`

as soon as me put a directive it crashes

### Expected behavior

no crash

### Actual behavior

![image](https://github.com/remarkjs/remark-directive/assets/1911240/95f784e9-4cad-4d4f-b992-ee026bfe3c0a)

![image](https://github.com/remarkjs/remark-directive/assets/1911240/3773bc87-ba20-4a23-9b3e-e2b3d240a035)

### Runtime

Node v17

### Package manager

npm 8

### OS

macOS

### Build and bundle tools

Vite

**Comment by ChristianMurphy** [comment] 2023-09-25 14:09
Welcome @mbret! 👋 
Sorry you ran into a spot of trouble.

A major version release is rolling out across all: `unified`, `remark`, `rehype`, and `micromark` packages.
This includes both type changes (static analysis error) and changes to the parser (potential runtime error) if the major versions are mismatched.

For now pin the version of `remark-directive` to the previous major until the new `react-markdown` major is released

**Comment by ChristianMurphy** [comment] 2023-09-25 14:09
Duplicate of https://github.com/remarkjs/react-markdown/issues/763

**Closed by ChristianMurphy** 2023-09-25 14:09 UTC
Labels: 🤞 phase/open

**Comment by mbret** [comment] 2023-09-25 14:43
> Duplicate of [remarkjs/react-markdown#763](https://github.com/remarkjs/react-markdown/issues/763)

indeed there is also a crash with latest version of rehype, which we are not using at the moment for the same reason

**Comment by ChristianMurphy** [comment] 2023-09-25 14:53
Bb offered some insight on that

> Because we treat issues as our backlog, we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn’t an exact duplicate but is closely related.

The underlying cause is the same.
`react-markdown` needs a new major release.
The unified community does not need 30+ issues (and counting) to track one update.

We appreciate the excitement, please be patient.

**Comment by nekorytaylor666** [comment] 2023-11-09 09:06
any updates on this. have the same error.

**Comment by wooorm** [comment] 2023-11-09 09:08
Update your dependencies
