### ISSUE TITLE
"error Cannot process file [cause]: TypeError: chunks[startIndex].slice is not a function" parsing Markdown with unclosed directive syntax

### ISSUE THREAD

**Issue by DavidAnson** [remarkjs/remark-directive#17] opened 2024-05-21 06:48 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-cli@12.0.1, remark-directive@3.0.0

### Steps to reproduce

See underlying `micromark` issue for context: https://github.com/micromark/micromark/issues/173

I've opened this separate issue for the awareness of the folks who maintain `remark`.

```bash
user@HOST mmi % npm ls
mmi@ /Users/user/Documents/mmi
├── micromark-extension-directive@3.0.0
├── micromark@4.0.0
├── remark-cli@12.0.1
└── remark-directive@3.0.0

user@HOST mmi % cat bug.md
* some text
   :::note

a%
user@HOST mmi % ./node_modules/.bin/remark bug.md --use remark-directive
bug.md
 error Cannot process file
  [cause]:
    TypeError: chunks[startIndex].slice is not a function
    at sliceChunks (file:///Users/user/Documents/mmi/node_modules/micromark/lib/create-tokenizer.js:512:32)
    at Object.sliceStream (file:///Users/user/Documents/mmi/node_modules/micromark/lib/create-tokenizer.js:153:12)
    at subcontent (file:///Users/user/Documents/mmi/node_modules/micromark-util-subtokenize/index.js:150:24)
    at subtokenize (file:///Users/user/Documents/mmi/node_modules/micromark-util-subtokenize/index.js:71:30)
    at postprocess (file:///Users/user/Documents/mmi/node_modules/micromark/lib/postprocess.js:12:11)
    at fromMarkdown (file:///Users/user/Documents/mmi/node_modules/mdast-util-from-markdown/lib/index.js:174:5)
    at parser (file:///Users/user/Documents/mmi/node_modules/remark-parse/lib/index.js:33:12)
    at Function.parse (file:///Users/user/Documents/mmi/node_modules/unified/lib/index.js:668:12)
    at parse (file:///Users/user/Documents/mmi/node_modules/unified-engine/lib/file-pipeline/parse.js:59:36)
    at wrapped (file:///Users/user/Documents/mmi/node_modules/trough/lib/index.js:160:27)

✖ 1 error
user@HOST mmi %
```

### Expected behavior

Can process file

### Actual behavior

Cannot process file (see above)

### Runtime

Node v17

### Package manager

npm 8

### OS

macOS

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by ChristianMurphy** [comment] 2024-05-21 11:47
Possibly a duplicate of the continuation error from https://github.com/micromark/micromark-extension-directive/issues/16

**Comment by ChristianMurphy** [comment] 2024-05-21 11:55
> I've opened this separate issue for the awareness of the folks who maintain remark.

For reference, pretty much the same team.

**Comment by ChristianMurphy** [comment] 2024-05-21 11:56
Closing this copy as it is an issue in a lower level dependency.

**Closed by ChristianMurphy** 2024-05-21 11:56 UTC
Labels: 👯 no/duplicate, 🤞 phase/open
