### ISSUE TITLE
Trailing whitespace is removed

### ISSUE THREAD

**Issue by christianvoigt** [remarkjs/remark-directive#16] opened 2024-05-08 08:48 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-directive 3.0.0

### Link to runnable example

[example](https://codesandbox.io/p/devbox/angry-rosalind-z9skr8?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvxkdw9200073b6klxdtho15%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvxkdw9100023b6k4ce1h29c%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvxkdw9100043b6kyv97h3fg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvxkdw9200063b6kpyslatwd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvxkdw9100023b6k4ce1h29c%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvxkdw9100013b6kjhql11kt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvxkh4go003f3b6k8z83qkmg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A9%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A16%252C%2522endColumn%2522%253A7%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fmain.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvxkdw9100023b6k4ce1h29c%2522%252C%2522activeTabId%2522%253A%2522clvxkh4go003f3b6k8z83qkmg%2522%257D%252C%2522clvxkdw9200063b6kpyslatwd%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvxkdw9200053b6kzqjt6j2i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvxkdw9200063b6kpyslatwd%2522%252C%2522activeTabId%2522%253A%2522clvxkdw9200053b6kzqjt6j2i%2522%257D%252C%2522clvxkdw9100043b6kyv97h3fg%2522%253A%257B%2522id%2522%253A%2522clvxkdw9100043b6kyv97h3fg%2522%252C%2522activeTabId%2522%253A%2522clvxkm0yt00923b6i80tm53v2%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvxkdw9100033b6kte54bvrc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522clvxkm0yt00923b6i80tm53v2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clvxkm140001tdjez7uv08ebh%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

I am using remark-directives to mark up deleted and inserted text ranges within paragraphs (similar to critic markup). I use `:del[old text ]` and `:ins[new text ]` for this. 

Currently, remark-directive does not respect empty spaces around the text. I saw https://github.com/remarkjs/remark-directive/issues/1 but think my case is slightly different as I use normal Markdown inside of the directive that should not be affected by putting it inside a directive. I don't see code fences as a viable workaround in this case.

### Expected behavior

The trailing whitespace should be preserved.

### Actual behavior

The trailing whitespace is removed.

### Runtime

Node v17

### Package manager

npm 8

### OS

macOS

### Build and bundle tools

Webpack

**Comment by wooorm** [comment] 2024-05-08 09:05
Hi!

Duplicate of micromark/micromark-extension-directive#22

**Closed by wooorm** 2024-05-08 09:05 UTC
Labels: 🤞 phase/open
